site_name: COMP423 Course Notes
theme:
  name: material

markdown_extensions:
# Admonition Extension
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Annotations Extension
  - attr_list
  - md_in_html
  - pymdownx.superfences

# List Extension 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# Code Blocks Extension
   - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences